### PR TITLE
Quantity fix

### LINKED ISSUE #608: Overwriting value on a Quantity
See this issue for full details: https://jira.hl7.org/browse/FHIR-28552.

When an author sets `value` on a Quantity, and then sets the Codeable properties on that Quantity as in the following:
```
* dosage.doseAndRate.doseQuantity.value = 250.0
* dosage.doseAndRate.doseQuantity = UCUM#mg "mg"
```
SUSHI overwrites the setting of `value` when setting the Codeable properties in the second line.

### PR DESCRIPTION
**Pull request by julianxcarter**
Fixes #608 in which setting a quantity value, then setting the rest of the quantity fields in a succeeding line would overwrite the previously set value.

### CODE REVIEW

File: src/fhirtypes/common.ts [hunk 1]
```diff
@@ -198,6 +198,20 @@ export function setPropertyOnInstance(
           if (current[key] == null) current[key] = {};
           current = current[key];
         } else {
+          // Check if the instance  already has the element being defined
+          if (current.hasOwnProperty([pathPart.base])) {
```
Comment (mint-thompson) [inline src/fhirtypes/common.ts:202]: I'm surprised this works, but it clearly does. The [MDN page for hasOwnProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty) doesn't mention taking an array parameter, though, so I would suggest passing the argument as a string rather than an array.

File: src/fhirtypes/common.ts [hunk 2]
```diff
@@ -198,6 +198,20 @@ export function setPropertyOnInstance(
...
+            // Check if the instance already has a quantity element
+            // Quantity elements are the only FHIR types with both a code and value
+            if (current[pathPart.base].hasOwnProperty('value')) {
+              if (assignedValue.hasOwnProperty('code')) {
```
Comment (mint-thompson) [inline src/fhirtypes/common.ts:206]: The conditions in the three if statements can safely be combined into a single if statement, since the only code that modifies data is nested inside all three.

File: src/fhirtypes/common.ts (hunk 1 above)
Comment (cmoesel) [inline src/fhirtypes/common.ts:202]: I'm confused by the array syntax here.  Why `current.hasOwnProperty([pathPart.base])` and not `current.hasOwnProperty(pathPart.base)`?  Is it just a left-over of a previous version where maybe you previously had `current[pathpart.base]`?  Or is there some other new fancy syntax thing I don't know about?  After all, it seems to work -- so I'm inclined to think maybe it was intentional!

It's not a big deal, but we could be a little more specific here and check that it's actually an object:
```ts
if (current[pathPart.base] != null && typeof current[pathPart.base] === 'object') {
```

**Review by mint-thompson — CHANGES_REQUESTED** [review]
Great work on your first PR! I have a few minor stylistic questions, but also, the test case you've written doesn't actually make it to your third if statement. So, I think you'll need to modify the test case to satisfy all of your conditions.

**Review by cmoesel — COMMENTED** [review]
First PR!  Awesome!  I had one question about a syntax I'm not familiar with...

File: src/fhirtypes/common.ts (hunk 1 above)
Comment (cmoesel) [reply src/fhirtypes/common.ts:202]: Oh.  I see @mint-thompson already noted this (in addition to some things I missed).  Thanks, @mint-thompson!

Comment (julianxcarter) [reply src/fhirtypes/common.ts:202]: Looking at this now, I'm actually surprised that it works as well haha. The brackets were a holdover from a previous implementation that I somehow glanced over a few times before I pushed this PR. I'll remove this in an edit, and then combine the three conditionals as well.

Comment (julianxcarter) [reply src/fhirtypes/common.ts:202]: It's not intentional! It was a holdover from a previous implementation where I was checking if `current[pathPart.base]` was truthy rather than using the `hasOwnProperty()` function. Looking at it now, I'm actually somewhat surprised it still worked! I also think that checking that it's actually an object would be useful, I'll add that app in another commit.

**Review by mint-thompson — DISMISSED** [review]
Hooray!

File: src/fhirtypes/common.ts [hunk 3]
```diff
@@ -198,6 +198,21 @@ export function setPropertyOnInstance(
           if (current[key] == null) current[key] = {};
           current = current[key];
         } else {
+          // Check if the instance already has the element being defined
+          if (current[pathPart.base] != null && typeof current[pathPart.base] === 'object') {
```
Comment (cmoesel) [inline src/fhirtypes/common.ts:202]: I just noticed this now, but I'm wondering... why do you use `current[pathPart.base]` here (and after) rather than `current[key]`?  I only noticed this because on line 211, we essentially assign `assignedValue.value` to `current[pathPart.base].value`, then on line 216, we assign `current[key] = assignedValue`.  So if you follow along, we say we're preserving the `value` but we're basically doing `current[key].value = current[pathPart.base].value`; which really should only work if `key === pathPart.base`.

And sure enough, if you look up at lines 136-137 we have:
```ts
const key =
  pathPart.primitive && i < pathParts.length - 1 ? `_${pathPart.base}` : pathPart.base;
```
And we only get to your new code if `i === pathParts.length` so I think we do in fact know that `key === pathPart.base` 100% of the time we are in this block (lines 201-215).  So... to me, it would be more clear if we just used `current[key]` instead of `current[pathPart.base]` since the code directly above and below this uses `current[key]` already.

**Review by cmoesel — COMMENTED** [review]
This looks really good.  I just have one minor question/suggestion I noticed as I reviewed it a second time.

File: src/fhirtypes/common.ts (hunk 3 above)
Comment (julianxcarter) [reply src/fhirtypes/common.ts:202]: You're right! Using `pathPart.base` isn't necessary when the `key` value is set to be the same thing on lines 136-137. There's no particular reason for my not using the `key` variable here, I had just blanked on the fact that they should always be equal in this block of code. I'll update the conditionals on lines 202 and below to use the `key` variable.

**Review by cmoesel — APPROVED** [review]
Looks great!  Thanks, @julianxcarter!

**Comment by cmoesel** [comment]
Given that the changes are trivial since @mint-thompson last approved, I am going to go ahead and merge this now.
