### PR TITLE
Set . path as context

### LINKED ISSUE #887: SUSHI incorrectly handles indented rules below a dot path
```
Extension: TestExtension
* ^context.type = #element
* ^context.expression = "Patient"
* . 0..1
  * ^short = "A test extension."
  * ^definition = "Yep.  It is a test extension."
* value[x] only boolean
```

In SUSHI 2.0.0 beta.1, this works correctly.  In SUSHI 2.0.0 beta.2, this results in the following errors:
```
error Rule cannot be indented below rule which has no path. The rule will be processed as if it is not indented.
  File: /Users/cmoesel/dev/fsh/TestBadThings/input/fsh/patient.fsh
  Line: 5
error Rule cannot be indented below rule which has no path. The rule will be processed as if it is not indented.
  File: /Users/cmoesel/dev/fsh/TestBadThings/input/fsh/patient.fsh
  Line: 6
```
and then later on in the log:
```
error The element or path you referenced does not exist: short
  File: /Users/cmoesel/dev/fsh/TestBadThings/input/fsh/patient.fsh
  Line: 5
error The element or path you referenced does not exist: definition
  File: /Users/cmoesel/dev/fsh/TestBadThings/input/fsh/patient.fsh
  Line: 6
```

### PR DESCRIPTION
**Pull request by mint-thompson**
Fixes #887.

When a rule's path is ".", the rule applies to the root element. Allow these rules to set a context so that they may be followed by an indented caret rule with no path.

Basically, the check for "did we indent a rule with a . path" was happening a bit too early. Now, when we have a . path on a rule with no indent, we'll first check that we're not indented, and therefore everything is fine.

### CODE REVIEW

File: src/import/FSHImporter.ts [hunk 1]
```diff
@@ -2078,6 +2065,17 @@ export class FSHImporter extends FSHVisitor {
     }
 
     // Otherwise, get the context based on the indent level.
+    if (path.length === 1 && path[0] === '.') {
```
Comment (ngfreiter) [inline src/import/FSHImporter.ts:2068]: I think this comment needs to be moved down below this new block.

**Review by ngfreiter — APPROVED** [review]
👍 🆒

**Review by julianxcarter — APPROVED** [review]
