### PR TITLE
Unfold Content Reference Elements

### LINKED ISSUE #184: Bug: error: Cannot read property 'length' of undefined
The following FSH file generates the error:
error: Cannot read property 'length' of undefined

But the same input with the extension on `compose.include.extension` instead works just fine.

```fsh
Profile: BoostedValueSet
Parent: ValueSet
Id: boostedvalueset
Title: "Boosted ValueSet"
Description: "Any ValueSet that uses the ValueSetBoost extension"
* compose.exclude.extension contains ValueSetBoost 0..* 

Extension: ValueSetBoost
Id: boost
Title: "ValueSet boosting"
Description: "boosting extension"
* value[x] only decimal
```

### PR DESCRIPTION
**Pull request by ngfreiter**
Fixes #184.

When we access the children of an element that has a contentReference field on it, we need to unfold from the element on the StructureDefinition that the contentReference refers to. A contentReference is used to refer to an element defined in that same StructureDefinition. Documentation on contentReferences is here https://www.hl7.org/fhir/elementdefinition-definitions.html#ElementDefinition.contentReference. 

This adds the capability to access children of an element that is a contentReference. Accessing a child will unfold all the children of the referenced element onto the element with the contentReference. The contentReference element will also have the contentReference field deleted, since it is no longer a contentReference. If you want to test on a real example, try adding the Profile on ValueSet described in #184 to a FSH file. You should see that the "exclude" element gets unfolded with the children of the "include" element, and constraints are correctly applied to it.

### CODE REVIEW

File: src/fhirtypes/ElementDefinition.ts [hunk 1]
```diff
@@ -1408,16 +1408,42 @@ export class ElementDefinition {
...
    * @returns {ElementDefinition[]} the unfolded elements or an empty array if the type is multi-value or type can't
    *   be resolved.
    */
   unfold(fisher: Fishable): ElementDefinition[] {
     if (
-      this.type.length === 1 &&
-      (this.type[0].profile == null || this.type[0].profile.length <= 1)
+      (this.type?.length === 1 &&
+        (this.type?.[0].profile == null || this.type?.[0].profile.length <= 1)) ||
+      this.contentReference
```
Comment (cmoesel) [inline src/fhirtypes/ElementDefinition.ts]: No offense, but this `if` statement is kind of ugly.  I'm trying to think of how it can be simplified or made neater.

If the logic made it through `this.type?.length === 1`, then we know `this.type` exists, so we don't need to do `this.type?` in `and`ed phrases after that.  I also think that line 1420 can be simplified.  I *think* this might be equivalent to the above:

```ts
(this.type?.length === 1 && !(this.type[0].profile?.length > 1)) ||
this.contentReference
```

Is that better or is the inversion more confusing?

Comment (ngfreiter) [reply src/fhirtypes/ElementDefinition.ts]: Am I missing something, or is there a reason not to just do:

Comment (ngfreiter) [reply src/fhirtypes/ElementDefinition.ts]: Isn't this the same:
```
(this.type?.length === 1 && this.type[0].profile?.length <= 1) ||
this.contentReference
```
Were you just adding the inversion because it seems more clear?

Comment (cmoesel) [reply src/fhirtypes/ElementDefinition.ts]: That's not the same because in that one, if `profile` is null then it evaluates to `false`, whereas we want a null profile to evaluate to `true`.  If you wanted to do it that way, we'd have to do something more like:
```ts
(this.type?.length === 1 && (this.type[0].profile ?? []).length <= 1) ||
this.contentReference
```
I'd be fine with that too if you think it is more clear.

Comment (ngfreiter) [reply src/fhirtypes/ElementDefinition.ts]: Ah wait nevermind, they are different if `profile` is null

Comment (cmoesel) [reply src/fhirtypes/ElementDefinition.ts]: I actually think that one I just did is more clear than my original suggestion.  So it's got my vote for whatever that is worth. ;-)

Comment (ngfreiter) [reply src/fhirtypes/ElementDefinition.ts]: Alright I'm sold, I'll do that last one. And I'll add an instance test

**Comment by ngfreiter** [comment]
Ok @cmoesel, I updated to use that cheeky if statement, and to add a test to the instance exporter.
